In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [3]:
x.dtype

dtype('int64')

In [4]:
x1 = np.array([1, 2, 3, 4], dtype = np.int64)
x1

array([1, 2, 3, 4])

Набор размерность по всем осям, которые есть в массиве.

In [5]:
x1.shape

(4,)

In [6]:
matrix = np.array([[1, 2, 3], [5, 6, 7]])

In [7]:
matrix.shape

(2, 3)

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
np.random.random((2,3))

array([[0.24835791, 0.11685224, 0.28982293],
       [0.8921944 , 0.97182902, 0.32122344]])

In [12]:
x1[2]

3

In [13]:
x1[0]

1

In [14]:
y = np.array([[1, 3, 4, 4],[2, 3, 4, 56]])

In [15]:
y[1, 3]

56

In [16]:
y[:, :3]

array([[1, 3, 4],
       [2, 3, 4]])

In [17]:
y > 2

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [18]:
y[y > 2]

array([ 3,  4,  4,  3,  4, 56])

In [19]:
b = np.array([[1, 3, 4, 4, 5],[2, 3, 4, 56, 5]])

In [20]:
b.shape

(2, 5)

In [21]:
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [22]:
b.T

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [23]:
b.reshape((10, 1))

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [24]:
b.resize((10, 1))

In [25]:
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [26]:
v = np.array([9, 10])
w = np.array([11, 12])

In [27]:
v + w

array([20, 22])

In [28]:
np.add(v, w)

array([20, 22])

In [29]:
v - w

array([-2, -2])

In [30]:
np.subtract(v, w)

array([-2, -2])

In [31]:
v * w

array([ 99, 120])

In [32]:
np.multiply(v, w)

array([ 99, 120])

In [33]:
np.dot(v, w)

219