In [1]:
from scipy import linalg
from scipy import optimize
import numpy as np
import matplotlib.pyplot as plt

## 1

Какие из следующих методов numpy не создают массивы, заполненные значениями (например массивы, состоящие из единиц или случайных чисел)?

In [2]:
np.full(3, 6)

array([6, 6, 6])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.randint(4, size = 10)

array([3, 2, 1, 2, 3, 0, 1, 1, 2, 3])

## 2

Найти число уникальных элементов в массиве

In [5]:
A = np.array([[3, 3, 3], [1, 3, 4], [7, 1, 3]])

In [6]:
len(np.unique(A))

4

## 3

Поменять порядок элементов в массиве на обратный и вернуть 4-й элемент нового массива Z = np.array([92, 13, 44, 555, 1, -3]).

Напомним, что индексация массива начинается с нуля.

In [7]:
Z = np.array([92, 13, 44, 555, 1, -3])
Znew = np.flip(Z)
Znew[4]

13

## 4

Создайте два вектора - вектор, состоящий из 5 единиц, и другой вектор размером 5, содержащий только значение 2. Найдите скалярное произведение векторов.

In [8]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [9]:
b = np.full([5], 2)
b

array([2, 2, 2, 2, 2])

In [10]:
np.dot(a, b)

10.0

## 5

Найти произведение двух матриц и вернуть диагональные элементы получившейся матрицы

In [11]:
m1 = np.array([[0, 9, 19, 13], [1, 20, 5, 13], [12, 11, 3, 4]])
m1

array([[ 0,  9, 19, 13],
       [ 1, 20,  5, 13],
       [12, 11,  3,  4]])

In [12]:
m2 = np.array([[2, 0, 0, 0], [1, 2, 2, 0], [2, 1, 1, 0], [0, 0, 1, 1]])
m2

array([[2, 0, 0, 0],
       [1, 2, 2, 0],
       [2, 1, 1, 0],
       [0, 0, 1, 1]])

In [13]:
np.diag(np.dot(m1, m2))

array([47, 45, 29])

## 6
Найти среднее значение элементов массива b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])

In [14]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])


In [15]:
np.sum(b) / len(b.flatten())

4.875

## 7
При помощи инструментов SciPy ответьте на следующие вопросы.
Является ли данная система векторов линейно независимой [6, 0, 3], [0, -1, 2], [12, 3, 0]?


Если определитель равен нулю, то вектора-строки или столбцы матрицы - линейно зависимы.

In [16]:
a1 = np.array([[6, 0, 3],[0, -1, 2],[12, 3, 0]])

In [17]:
linalg.det(a1)

0.0

## 8

Найти собственные значения матрицы

In [18]:
A = np.array([[1, -1, -1, 0],
              [-1, 2, -1, -1],
              [-1, -1, 2, -1],
              [0, -1, -1, 1]])

In [19]:
A

array([[ 1, -1, -1,  0],
       [-1,  2, -1, -1],
       [-1, -1,  2, -1],
       [ 0, -1, -1,  1]])

In [20]:
eigenvalues, eigenvectors = linalg.eig(A)

In [21]:
eigenvalues

array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j])

## 9
Найти обратную матрицу и след обратной матрицы (сумма элементов главной диагонали)

In [22]:
nine = np.array([[2, 4, 0, 4, 1],
                 [2, 4, 1, 1, 0],
                 [1, 1, 1, 2, 2],
                 [0, 1, 3, 2, 4],
                 [2, 2, 2, 0, 2]])
nine

array([[2, 4, 0, 4, 1],
       [2, 4, 1, 1, 0],
       [1, 1, 1, 2, 2],
       [0, 1, 3, 2, 4],
       [2, 2, 2, 0, 2]])

In [23]:
nineinv = linalg.inv(nine)

In [24]:
np.sum(np.diag(nineinv))

2.700000000000001